### ISSUE TITLE
[🛠Error_log] #41 AWS The overall deployment failed because too many individual instances failed deployment

### ISSUE THREAD

**Issue by james-taeil** [codestates/AllAboutMe#106]
### 어떤 에러인가요?
- AWS Codepipeline 배포 중 실패 

### 에러 메시지
$ The overall deployment failed because too many individual instances failed deployment, too few healthy instances are available for deployment, or some instances in your deployment group are experiencing problems.

$ The CodeDeploy agent did not find an AppSpec file within the unpacked revision directory at revision-relative path "appspec.yml". The revision was unpacked to directory "/opt/codedeploy-agent/deployment-root/0de3e1e6-516b-4fbd-b510-e83dac614b45/d-N83CXI5WB/deployment-archive", and the AppSpec file was expected but not found at path "/opt/codedeploy-agent/deployment-root/0de3e1e6-516b-4fbd-b510-e83dac614b45/d-N83CXI5WB/deployment-archive/appspec.yml". Consult the AWS CodeDeploy Appspec documentation for more information at 

### 에러 핸들링 방법
- 1차 시도 : 오타 fix >>> 같은 오류 실패
- 2차 시도 : file명 correct >>> 같은 오류 실패
- 3차 시도 : scripts 파일 안에 sh파일 넣기 >>> 같은 오류 실패
- 4차 시도 : index.js, const port = 4000; 변경
- 5차 시도 : 개인 Repo에 push 해서 코드를 수정 후 배포 : 성공

// 코드가 들어가도 좋아요!

**Comment by cue28** [comment]
고생하셨습니다 🙂

**Comment by soowan-jang** [comment]
해결 굿 :)
